### ISSUE TITLE
Can not use prebuilt binaries Linux

### ISSUE THREAD

**Issue by 7fold** [Koromix/luigi#10]
Hi @Koromix. I'm having issues using `koffi` on Linux, however, it works great on Windows.

Details:
```
 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /proj/node_modules/koffi/build/koffi.node)

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:893:29)
      at Object.<anonymous> (node_modules/koffi/src/index.js:21:18)

```

ENV:

- Node: v16.15.1
- OS: Debian GNU/Linux 9.5 (stretch)

**Comment by Koromix** [comment]
Hi,

The problem is that your glibc is older than the prebuilt one. Which is something I should have thought of :) The old glibc problem... I use Debian 11 for the Linux builds.
I'm working on a system to check if the prebuilt binary works, and if not, build from source automatically when the package is installed.

It should come quickly :)

Thanks!

**Comment by Koromix** [comment]
This should work in Koffi 1.3.1 :)

Of course, this means you need to installer a compiler (GCC) and CMake, and it needs to be recent enough. Hopefully this is the case in your distribution, if not let me know and I will find something else ;)

**Comment by Koromix** [comment]
I've just tried Debian 9.5 in a VM, man that's old :) What Node.js version do you have (`node --version`)? And GCC (`gcc --version`)?
