### ISSUE TITLE
Missing `koffi.node` module in the build folder

### ISSUE THREAD

**Issue by 7fold** [Koromix/luigi#11]
Hi @Koromix . I've noticed another weird bug, related to missing `koffi.node` module in the ` 'C:\proj\node_modules\koffi\src/../build/koffi.node'`. (Path looks like this because of https://github.com/Koromix/luigi/blob/cd839b5895146cda8709992278bb183bb9e48f32/koffi/src/index.js#L20, and might be better to replace with `let filename = path.resolve(path.dirname(__filename), '../build/koffi.node')`).

But after checking `node_modules\koffi\build\` folder, it was actually missing `koffi.node`, and I'm not sure why. Tried deleting `node_modules`, manually running `npm install koffi`, etc, and re-running the install, but wasn't helpful. It works fine on macOS, Linux, and Windows machines, however, got this error on another Windows 10 Pro Azure remote desktop machine.

**Comment by Koromix** [comment]
Hi,

The first explanation that comes to mind, is that the prebuilt binary fails to load and is thus deleted from the build folder. And then, the install script tries to build Koffi from source, but this also fails (maybe no compiler is available).

The install output should tell what goes wrong. Could you post the result of these commands?

```
cd node_module\koffi
npm install
```

Also, what is the Node version in use on this machine?

```
node --version
```

**Comment by 7fold** [comment]
It happens on Windows 10 using node v14 (v14.17.1 to be exact)

And the output log looks like this:
```
username@domain MINGW64 ~/Desktop/proj/node_modules/koffi (master)
$ npm install

> cpu-features@0.0.4 install C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cpu-features
> node buildcheck.js > buildcheck.gypi && node-gyp rebuild


C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cpu-features>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  
else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  impl_aarch64_linux_or_android.c
  impl_arm_linux_or_android.c
  impl_mips_linux_or_android.c
  impl_ppc_linux.c
  impl_x86_freebsd.c
  impl_x86_linux_or_android.c
  impl_x86_macos.c
  impl_x86_windows.c
  filesystem.c
  stack_line_reader.c
  string_view.c
  win_delay_load_hook.cc
  cpu_features.vcxproj -> C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cpu-features\build\Release\\cpu_features.lib
  binding.cc
  win_delay_load_hook.cc
     Creating library C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cpu-features\build\Release\cpufeatures.lib and object C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cpu-features\build\Release\cpufeatures.exp       
  cpufeatures.vcxproj -> C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cpu-features\build\Release\\cpufeatures.node

> ref-napi@3.0.3 install C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ref-napi
> node-gyp-build


> ssh2@1.11.0 install C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ssh2
> node install.js


C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ssh2\lib\protocol\crypto>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --target=v14.17.1 --real_openssl_major=1 rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --target=v14.17.1 --real_openssl_major=1 rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
     Creating library C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ssh2\lib\protocol\crypto\build\Release\sshcrypto.lib and object C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ssh2\lib\protocol\crypto\build\Release 
  \sshcrypto.exp
  sshcrypto.vcxproj -> C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ssh2\lib\protocol\crypto\build\Release\\sshcrypto.node
Succeeded in building optional crypto binding

> ffi-napi@4.0.3 install C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ffi-napi
> node-gyp-build


C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Preprocessing assembly file ..\..\..\deps\libffi\src\x86\win64_intel.preasm
  win64_intel.preasm
  Building assembly file Release\obj\ffi\\win64_intel.asm
   Assembling: Release\obj\ffi\win64_intel.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffiw64.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ffi-napi\build\Release\\libffi.lib
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ffi-napi\build\Release\\nothing.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
     Creating library C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ffi-napi\build\Release\ffi_bindings.lib and object C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ffi-napi\build\Release\ffi_bindings.exp
  ffi_bindings.vcxproj -> C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\ffi-napi\build\Release\\ffi_bindings.node

> raylib@0.9.2 postinstall C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\raylib
> node tools/postinstall.js || npm run compile

Checking for https://github.com/RobLoach/node-raylib/releases/download/v0.9.2/node-raylib-4.0-win32-x64.node
Found on releases.

> koffi@1.3.5 install C:\Users\username\Desktop\proj\node_modules\koffi
> cnoke --prebuild build/qemu/{{version}}/koffi_{{platform}}_{{arch}}.tar.gz --require ./build/koffi.node

(node:4048) UnhandledPromiseRejectionWarning: TypeError: dirname.replaceAll is not a function
    at find_parent_directory (C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cnoke\cnoke.js:750:27)
    at main (C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cnoke\cnoke.js:161:19)
    at Object.<anonymous> (C:\Users\username\Desktop\proj\node_modules\koffi\node_modules\cnoke\cnoke.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 49 packages from 117 contributors and audited 51 packages in 31.09s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
After updating to node v16, this problem was resolved.

**Comment by Koromix** [comment]
Thanks for the log! The problem was in the build system and not Koffi directly.

I've tested it on old Node.js versions, but on Linux and not on Windows. And the `replaceAll` (pretty recent in JS) function was only used on Windows...

I'll make a new release soon!

Thanks :)
